name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: install dependency
      run: |
        npm install

    - name: Build app
      run: npm run build
    - name: Deploy app
      run: |
        git config --global user.email "syafawi666@gmail.com"
        git config --global user.name "achmadSyafawi"
        npm run deploy
        
